import { initChecklist } from './checklist';
import { initGlossary } from './glossary';
import { initCoach } from './mascot';
import { initBackups } from './missions/backups';
import { initCastle } from './missions/castle';
import { initChats } from './missions/chat';
import { initEncryption } from './missions/encryption';
import { initExams } from './missions/exam';
import { initFinish } from './missions/finish';
import { initInbox } from './missions/inbox';
import { initLeakHunt } from './missions/leak-hunt';
import { initPasswordLab } from './missions/password-lab';
import { initPermissions } from './missions/permissions';
import { initPublicWifi } from './missions/public-wifi';
import { initQuizzes } from './missions/quiz';
import { initResponsePlans } from './missions/response-plan';
import { initSorters } from './missions/sorter';
import { initTwoFactor } from './missions/two-factor';
import { initUrlLabs } from './missions/url-lab';
import { initVault } from './missions/vault';
import { initPrint, initReveal, initToast } from './reveal';
import { initSound } from './sound';

initReveal();
initToast();
initPrint();
initCoach();
initSound();
initGlossary();
initChecklist();
initQuizzes();
initExams();
initSorters();
initCastle();
initPasswordLab();
initTwoFactor();
initVault();
initUrlLabs();
initInbox();
initChats();
initLeakHunt();
initPermissions();
initEncryption();
initPublicWifi();
initBackups();
initResponsePlans();
initFinish();
