import { initChecklist } from './checklist';
import { initGlossary } from './glossary';
import { initOnboarding } from './onboarding';
import { initCoach } from './mascot';
import { initBackups } from './missions/backups';
import { initCastle } from './missions/castle';
import { initChats } from './missions/chat';
import { initEncryption } from './missions/encryption';
import { initExams } from './missions/exam';
import { initFinish } from './missions/finish';
import { initHashLabs } from './missions/hash-lab';
import { initIncidents } from './missions/incident';
import { initInbox } from './missions/inbox';
import { initLeakHunt } from './missions/leak-hunt';
import { initLogHunts } from './missions/log-hunt';
import { initMissionNavigation } from './missions/navigation';
import { initPasswordLab } from './missions/password-lab';
import { initPermissions } from './missions/permissions';
import { initPublicWifi } from './missions/public-wifi';
import { initQuizzes } from './missions/quiz';
import { initResponsePlans } from './missions/response-plan';
import { initSorters } from './missions/sorter';
import { initTwoFactor } from './missions/two-factor';
import { initUrlLabs } from './missions/url-lab';
import { initVault } from './missions/vault';
import { initPasswordFields } from './password-fields';
import { initPath } from './path';
import { initPrint, initReveal, initToast } from './reveal';
import { initReview } from './review';
import { initSound } from './sound';

initReveal();
initToast();
initPrint();
initCoach();
initSound();
initGlossary();
initOnboarding();
initReview();
initChecklist();
initPasswordFields();
initPath();
initQuizzes();
initExams();
initSorters();
initCastle();
initPasswordLab();
initTwoFactor();
initVault();
initUrlLabs();
initInbox();
initChats();
initLeakHunt();
initPermissions();
initEncryption();
initPublicWifi();
initBackups();
initResponsePlans();
initHashLabs();
initIncidents();
initLogHunts();
initFinish();
initMissionNavigation();
